### ISSUE TITLE
Could bookmarking be renamed?

### ISSUE THREAD

**Issue by gramliu** [ScottyLabs/course-tool#4]
![image](https://user-images.githubusercontent.com/24856195/161089141-100748ee-9972-41ed-8244-e8b372187ffb.png)

When I first used it, it took me a while to realize that I needed to bookmark courses in order to see the total number of FCEs for my classes. What if we called it a "schedule" instead and replaced the bookmark button with a "plus" icon to "add to my schedule"? Then, we could replace the "Bookmarked" tab on the navbar with a "My Schedule" tab. This might make it more intuitive to new users

**Comment by btwj** [comment]
Resolved by #23
