### ISSUE TITLE
[Bootcamp] Match Courses in the Schedule Selector without Dashes

### ISSUE THREAD

**Issue by btwj** [ScottyLabs/course-tool#48]
### Task Brief

Modify the filtering for courses in the Schedule Explorer to match course codes without dashes.
The file that should be changed is `components/ScheduleSearch.tsx`.

### Expected Deliverables

Searching for courses on this page shouldn't require dashes, e.g. 15150 and 15-150 should pull up the same courses.

### Estimated Completion Time

1 hour

### Reviewers

@btwj

**Comment by Lhwhatever** [comment]
Closed in an unknown PR.
