### ISSUE TITLE
[Bootcamp] Make Schedule Links link to instructor pages

### ISSUE THREAD

**Issue by btwj** [ScottyLabs/course-tool#63]
### Task Brief

Right now, there are no links for instructors in the schedule card. Create a link to the correct instructor page if the name is not "TBA".

### Expected Deliverables

A link should be present similar to the FCE Browser.

### Estimated Completion Time

1 hour

### Reviewers

@btwj

**Comment by Lhwhatever** [comment]
this was complete in some past commit (no idea which one)
