### ISSUE TITLE
[Feature] Make it possible to ⌘/Ctrl + click a course to open it in a new tab

### ISSUE THREAD

**Issue by Nicolapps** [ScottyLabs/course-tool#89]
### Description

The current implementation of the course list doesn’t allow users to open a course’s page in a new tab by clicking it while holding ⌘/Ctrl. Allowing that would improve user experience.

**Comment by Nicolapps** [comment]
It looks like this issue might be automatically fixed when the project will be updated to Next.js 13, which [automatically uses `<a>` tags to render links](https://nextjs.org/blog/next-13#nextlink).

**Comment by Lhwhatever** [comment]
Closed by PR #96
